version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running application build
      - python app.py  
artifacts:
  files:
    - '**/*'  
  discard-paths: yes
